(defproject account-dashboard "1.0"
  :dependencies [[cljs-ajax "0.5.8"]
                 [com.cemerick/url "0.1.1"]
                 [day8.re-frame/http-fx "0.1.3"]
                 [org.clojure/clojure "1.9.0"]
                 [org.clojure/clojurescript "1.9.946"]
                 [org.clojure/core.async "0.4.474"]
                 [cljsjs/d3 "4.12.0-0"]
                 [reagent "0.7.0"]
                 [reagent-utils "0.2.1"]
                 [re-frame "0.10.2"]
                 [re-com "2.1.0"]
                 [secretary "1.2.3"]
                 [cheshire "5.8.0"]
                 [binaryage/devtools "0.9.8"]
                 [figwheel-sidecar "0.5.9"]
                 [com.cemerick/piggieback "0.2.1"]]

  :plugins [[lein-shell "0.4.0"]
            [lein-cljsbuild "1.1.7"]
            [s3-wagon-private "1.3.1"]
            [lein-doo "0.1.8"]
            [lein-figwheel "0.5.14"]]
  )
